POST http://localhost:8080/domicilios HTTP/1.1
Content-Type: application/json

{
    "calle": "",
    "numero": 0
}

###

GET http://localhost:8080/domicilios

###

GET http://localhost:8080/domicilios/f4877513-00a4-4066-93f4-11de0b30dc5c

###

PUT http://localhost:8080/domicilios/ddf29576-66d4-4d9d-9ac1-4e647441cf8d HTTP/1.1
Content-Type: application/json

{
    "calle": "",
    "numero": 0
}

###

DELETE http://localhost:8080/domicilios/30589f53-28d0-4b28-bd65-ffdda6d74eb5